// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAotpv3YRHv-HyVyMSsIDcEgGheBpWCz7s',
    appId: '1:384190966837:web:95578b657fb8aa708ed57c',
    messagingSenderId: '384190966837',
    projectId: 'ferrer-advmobprog-frebase',
    authDomain: 'ferrer-advmobprog-frebase.firebaseapp.com',
    storageBucket: 'ferrer-advmobprog-frebase.firebasestorage.app',
    measurementId: 'G-SMGT7YYJWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiDzaDzmKLS2fOW30cz8BI0SdHGEF6K08',
    appId: '1:384190966837:android:a99795918e469add8ed57c',
    messagingSenderId: '384190966837',
    projectId: 'ferrer-advmobprog-frebase',
    storageBucket: 'ferrer-advmobprog-frebase.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa8W9KKhM0BEtMjLEOoZTW8uGFadbqQgo',
    appId: '1:384190966837:ios:80abf1229bbf8bc48ed57c',
    messagingSenderId: '384190966837',
    projectId: 'ferrer-advmobprog-frebase',
    storageBucket: 'ferrer-advmobprog-frebase.firebasestorage.app',
    iosBundleId: 'com.example.ferrerAdvmobpro2627',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa8W9KKhM0BEtMjLEOoZTW8uGFadbqQgo',
    appId: '1:384190966837:ios:80abf1229bbf8bc48ed57c',
    messagingSenderId: '384190966837',
    projectId: 'ferrer-advmobprog-frebase',
    storageBucket: 'ferrer-advmobprog-frebase.firebasestorage.app',
    iosBundleId: 'com.example.ferrerAdvmobpro2627',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAotpv3YRHv-HyVyMSsIDcEgGheBpWCz7s',
    appId: '1:384190966837:web:729c1c0c3d192a868ed57c',
    messagingSenderId: '384190966837',
    projectId: 'ferrer-advmobprog-frebase',
    authDomain: 'ferrer-advmobprog-frebase.firebaseapp.com',
    storageBucket: 'ferrer-advmobprog-frebase.firebasestorage.app',
    measurementId: 'G-N2GH2BKWKD',
  );
}
